#!/bin/bash

set -xe

trap "git worktree remove mkrelease || true" EXIT

release_notes=$(awk '/^## /{f=1;next} f{if(/^## /){f=0;exit} print}' CHANGELOG.md)
version=$(cargo pkgid -p me3-mod-host | cut -d '@' -f2)
tag_name="v$version"

if git rev-parse "$tag_name" >/dev/null 2>&1; then
    echo "Tag already exists for $tag_name"
    exit 1
fi

git fetch
git worktree add -B "release-$tag_name" mkrelease origin/main
(
    pushd mkrelease || exit 1

    readarray -t replacements < <(cargo metadata --format-version 1 | jq --compact-output '.metadata.release.pre_release_replacements[]')

    for replacement_json in "${replacements[@]}"; do
        search=$(echo "$replacement_json" | jq -r .search)
        template=$(echo "$replacement_json" | jq -r .replace)
        replacement=$(TAG_NAME="$tag_name" DATE=$(date +"%Y-%m-%d") envsubst <<<"$template")
        changelog=$(<CHANGELOG.md)

        echo "${changelog//"$search"/"$replacement"}" >CHANGELOG.md
    done

    git add CHANGELOG.md && git commit -S -s -m "Release: $version\n$release_notes"
    tag_sha=$(git rev-parse --verify HEAD)
    read -r -d '' tag_command_template <<'EOF'
# Create and publish the tag:

```
git tag --sign -a $TAG_NAME $TAG_SHA
gh release create --prerelease $TAG_NAME --notes-from-tag --verify-tag
```
EOF

    tag_command=$(TAG_NAME="$tag_name" TAG_SHA="$tag_sha" envsubst <<<"$tag_command_template")

    cargo set-version --bump minor
    new_version=$(cargo pkgid -p me3-mod-host | cut -d '@' -f2)

    git add Cargo.* && git commit -S -s -m "Release: Start $new_version development"
    git push origin "HEAD:release-$tag_name" --force

    gh pr create -B main -b "$release_notes\n$tag_command" --title "Release: $version"
)
