name: "Setup Windows toolchain"
description: "Install and set up the x86_64-pc-windows-msvc Rust toolchain"
runs:
  using: 'composite'
  steps:
    - name: Install LLVM
      shell: bash
      run: |
        sudo apt-get update
        sudo apt install --install-recommends lld clang-tools llvm wkhtmltopdf nsis

    - name: Cache MSVC SDK
      id: cache-xwin
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ github.workspace }}/xwin
        key: xwin

    - name: Fetch MSVC SDK
      if: steps.cache-xwin.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cargo install xwin --locked
        xwin --accept-license splat --output "${{github.workspace}}/xwin"

    - name: Generate x86_64-pc-windows-msvc configuration
      shell: bash
      run: |
        {
            CL_FLAGS="-Wno-unused-command-line-argument -fuse-ld=lld-link  /imsvc${{ github.workspace }}/xwin/crt/include  /imsvc${{ github.workspace }}/xwin/sdk/include/ucrt  /imsvc${{ github.workspace }}/xwin/sdk/include/um /imsvc${{ github.workspace }}/xwin/sdk/include/shared"

            echo "AR_x86_64_pc_windows_msvc=llvm-lib"
            echo "CFLAGS_x86_64_pc_windows_msvc=$CL_FLAGS"
            echo "CXXFLAGS_x86_64_pc_windows_msvc=$CL_FLAGS /EHsc"
            echo "CC_x86_64_pc_windows_msvc=clang-cl-18"
            echo "CXX_x86_64_pc_windows_msvc=clang-cl-18"
        } >>"$GITHUB_ENV"

        cat >~/.cargo/config.toml <<EOF
        [target.x86_64-pc-windows-msvc]
        linker = "lld"
        runner = ["env", "WINEDEBUG=-all", "wine"]
        rustflags = [
            "-Lnative=${{ github.workspace }}/xwin/crt/lib/x86_64",
            "-Lnative=${{ github.workspace }}/xwin/sdk/lib/um/x86_64",
            "-Lnative=${{ github.workspace }}/xwin/sdk/lib/ucrt/x86_64",
            "-C",
            "target-feature=+crt-static",
            "--cfg", "windows_debugger_visualizer"
        ]
        EOF
