version: 2

build:
  os: "ubuntu-24.04"
  apt_packages:
    - pngquant
  tools:
    python: "3"
  jobs:
    pre_install:
      - pip install -r docs/requirements.txt
mkdocs:
  configuration: mkdocs.yml
