version: 2

build:
  os: "ubuntu-24.04"
  apt_packages:
    - pngquant
  tools:
    python: "3"
  jobs:
    pre_install:
      - '[ -z "$GITHUB_MKDOCS_INSIDERS_TOKEN" ] && pip install -r docs/requirements.txt'
      - '[ ! -z "$GITHUB_MKDOCS_INSIDERS_TOKEN" ] && pip install -r docs/requirements-insiders.txt'
mkdocs:
  configuration: mkdocs.yml
