[files]
extend-exclude = ["CHANGELOG.md"]

[default]
extend-ignore-words-re = [
    "seh",    # structured exception handling
    "intoto",
]
extend-ignore-re = ["(?Rm)^.*(#|//)\\s*spellchecker:disable-line$"]
