[files]
extend-exclude = ["mkdocs.yml", "CHANGELOG.md", "docs/**/*.pl.md", "docs/**/*.zh.md"]

[default]
extend-ignore-words-re = [
    "seh",    # structured exception handling
    "intoto",
]
extend-ignore-re = ["(?Rm)^.*(#|//)\\s*spellchecker:disable-line$"]
