[package]
name = "me3-mod-host-api"
version = "0.9.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
me3-launcher-attach-protocol.workspace = true
serde_json.workspace = true

[lints]
workspace = true
