authors:
  gtierney:
    name: Gary Tierney
    description: Maintainer
    avatar: https://gravatar.com/avatar/584ab6ad3ab0cebb453ad9619ed187a90f5e1d63aab05ea2abff653521bbb0d3
  tremwil:
    name: William Tremblay
    description: Contributor
    avatar: https://avatars.githubusercontent.com/u/11468751?v=4