name: "Create Authenticode signature"
description: "Sign Windows PE files with against a remote signing server"
inputs:
  cloudflare_client_id:
    description: "OAuth2 client ID for Cloudflare Zero Trust Access"
  cloudflare_client_secret:
    description: "OAuth2 client secret for Cloudflare Zero Trust Access"
  signing-pin:
    description: "HSM authentication PUK"
  files: # id of input
    description: "Space delimited list of files to sign"
    required: true
runs:
  using: "composite"
  steps:
    - name: Get OIDC token
      id: get-oidc-token
      run: |
        TOKEN=$(curl -sSL -X GET "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=irithyll.me3.help" \
          -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq -r '.value')
        echo "value=$TOKEN" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Sign executables
      env:
        CF_ACCESS_CLIENT_ID: ${{ inputs.cloudflare_client_id }}
        CF_ACCESS_CLIENT_SECRET: ${{ inputs.cloudflare_client_secret }}
        GITHUB_TOKEN: ${{ steps.get-oidc-token.outputs.value }}
        FILES: ${{ inputs.files }}
      run: |
        for exe in $FILES; do
          echo "Signing $exe"
          curl -v --fail-with-body --compressed \
            -H "CF-Access-Client-Id: ${CF_ACCESS_CLIENT_ID}" \
            -H "CF-Access-Client-Secret: ${CF_ACCESS_CLIENT_SECRET}" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "X-Signing-Pin: ${{ inputs.signing-pin }}" \
            -H "X-Signing-Key: e25a03beabebbaa4b79fe76121540ec059794a60" \
            -H "Content-Type: application/vnd.microsoft.portable-executable" \
            --data-binary "@$exe" --output "$exe.signed" \
            https://irithyll.me3.help
          mv "$exe" "$exe.unsigned"
          mv  "$exe.signed" "$exe"
        done
      shell: bash
