name: Upload translation sources to Crowdin

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions: read-all

jobs:
  synchronize-with-crowdin:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: crowdin action
        uses: crowdin/github-action@8818ff65bfc4322384f983ea37e3926948c11745 # v2.15.0
        with:
          upload_sources: true
          config: crowdin.yml
        env:
          CROWDIN_PROJECT_ID: 805966
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
