on:
  workflow_dispatch:
  push:
    branches:
      - main
name: Create release PR
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  create-release-pr:
    name: Prerelease
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          token: ${{ secrets.PUSH_TOKEN }}
      - uses: taiki-e/install-action@dd154fff2f898f480894c915c12aa8782e93c71b # v2.53.1
        with:
          tool: cargo-set-version,git-cliff
      - run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"

          set +e
          # git-cliff uses GITHUB_TOKEN
          RELEASE_PUSH=1 GITHUB_TOKEN="$GH_TOKEN" ./releng/bin/create-release-pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
